### ISSUE TITLE
trackintel data format error

### ISSUE THREAD

**Issue by adonnini** [mie-lab/location-prediction#4]
Hi,
I am using your model with my dataset formatted like the geolife dataset.
Until last week, there was no problem completing the pre-processing step.. Since then, pre-processing fails with the traceback log reported below.

Below you will also find the input dataset which causes the failure.

Below, I also include an input dataset which does not cause pre-processing to fail.

I cannot see any difference between the two input datasets in terms of record structure.

I also do not quite understand the error message:

```
ValueError: time data "2024-0-2 7:0:57" at position 0 doesn't match format specified
```
Is the error message saying that one of the records in the dataset contains
```2024-0-2 7:0:57```? As you can see below no record in the dataset contains this pattern.

Could you please help me resolve this issue? What am I not seeing and/or doing wrong?

Thanks

TRACEBACK LOG
-------------------------
```
Traceback (most recent call last):
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/LocationPrediction/preprocessing/geolife.py", line 168, in <module>
    get_dataset(config=CONFIG, epsilon=args.epsilon)
  File "/home/adonnini1/Development/ContextQSourceCode/NeuralNetworks/LocationPrediction/preprocessing/geolife.py", line 26, in get_dataset
    pfs, _ = read_geolife(config["raw_geolife"], print_progress=True)
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/trackintel/io/dataset_reader.py", line 117, in read_geolife
    gdf = pd.concat(_get_df(geolife_path, uids, print_progress), axis=0, ignore_index=True)
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 422, in __init__
    objs = list(objs)
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/trackintel/io/dataset_reader.py", line 189, in _get_df
    data["tracked_at"] = pd.to_datetime(data["date"] + " " + data["time"], format="%Y-%m-%d %H:%M:%S", utc=True)
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 1068, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 438, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/home/adonnini1/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py", line 2177, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 427, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 599, in pandas._libs.tslib.array_to_datetime
ValueError: time data "2024-0-2 7:0:57" at position 0 doesn't match format specified
```

INPUT DATASET WHICH CAUSES FAILURE
-------------------------------------------------------------
```
Geolife trajectory
WGS 84
Altitude is in Feet
Reserved 3
0,2,255,My Track,0,0,2,8421376
0
42.96057621353667,-81.34552067527518,0,0,45293,2024-0-2,7:0:57
42.960854208386955,-81.3463197534195,0,0,45293,2024-0-2,7:0:57
42.96091271518786,-81.34635018147927,0,0,45293,2024-0-2,7:0:57
42.9737293483869,-81.32829863748867,0,0,45293,2024-0-2,7:0:57
42.973755004795365,-81.32842788316327,0,0,45293,2024-0-2,7:0:57
42.97564504340588,-81.32194977472004,0,0,45293,2024-0-2,7:0:57
42.97593313104018,-81.32199810424413,0,0,45293,2024-0-2,7:0:57
42.975969807381006,-81.32198093591352,0,0,45293,2024-0-2,7:0:57
42.9760710258729,-81.32179280518828,0,0,45293,2024-0-2,7:0:57
42.976106288386895,-81.32209860085274,0,0,45293,2024-0-2,7:0:57
42.9761150983869,-81.32209800082813,0,0,45293,2024-0-2,7:0:57
42.97624936154101,-81.32201358626166,0,0,45293,2024-0-2,7:0:57
42.97625405914777,-81.32214258413602,0,0,45293,2024-0-2,7:0:57
42.987786275880026,-81.32659013043525,0,0,45293,2024-0-2,7:0:57
42.99006595838683,-81.31835366186378,0,0,45293,2024-0-2,7:0:57
42.993750715746145,-81.30514688644925,0,0,45293,2024-0-2,7:0:57
43.000314908386756,-81.300993833221,0,0,45293,2024-0-2,7:0:57
```

SAMPLE INPUT DATASET WHICH DOES NOT CAUSE PRE-PROCESSING TO FAIL
--------------------------------------------------------------------------------------------------------------------
```
Geolife trajectory
WGS 84
Altitude is in Feet
Reserved 3
0,2,255,My Track,0,0,2,8421376
0
44.43645965890645,-81.40441678790644,0,0,45284,2023-11-24,18:16:17
44.43650193688819,-81.40460628161391,0,0,45284,2023-11-24,18:16:17
44.436505806041566,-81.40444538043556,0,0,45284,2023-11-24,18:16:17
44.436558719075165,-81.40496128823457,0,0,45284,2023-11-24,18:16:17
44.4365688055671,-81.40466895052742,0,0,45284,2023-11-24,18:16:17
44.43657726997211,-81.40477304125808,0,0,45284,2023-11-24,18:16:17
44.43657726997211,-81.40477304125808,0,0,45284,2023-11-24,18:16:17
44.436600603305465,-81.40471637458066,0,0,45284,2023-11-24,18:16:17
44.436608936638784,-81.40487637457682,0,0,45284,2023-11-24,18:16:17
44.436608936638784,-81.40487637457682,0,0,45284,2023-11-24,18:16:17
44.43662226997211,-81.40469804123732,0,0,45284,2023-11-24,18:16:17
44.43662226997211,-81.40469804123732,0,0,45284,2023-11-24,18:16:17
44.43667913937491,-81.40447871317181,0,0,45284,2023-11-24,18:16:17
44.43669060330546,-81.40472470787246,0,0,45284,2023-11-24,18:16:17
44.43669060330546,-81.40472470787246,0,0,45284,2023-11-24,18:16:17
44.43672993275473,-81.40442388112147,0,0,45284,2023-11-24,18:16:17
44.43678254039121,-81.40446641887749,0,0,45284,2023-11-24,18:16:17
```

**Comment by hongyeehh** [comment]
Hi,

The error message hints the problem comes from the incorrect date format. Your time data `2024-0-2 7:0:57` does not correspond to the specified `%Y-%m-%d %H:%M:%S`; e.g., it should instead be `2024-01-02 07:00:57`. Check the [description](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) of the time format for more details. 

I have tested that the repo runs without error in the Geolife dataset.
